version: '3.7'

networks:
  scholl_managnent_system:
    driver: bridge

services:
  identity_db:
    image: postgres:latest
    container_name: identity_container
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: always
    networks:
      - scholl_managnent_system
    volumes:
      - identity_db_data:/var/lib/postgresql/data
  
  science_db:
    image: postgres:latest
    container_name: science_container
    environment:
       POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    restart: always
    networks:
      - scholl_managnent_system
    volumes:
      - science_db_data:/var/lib/postgresql/data

volumes:
  identity_db_data:
  science_db_data: 
