version: '3.7'

services:
  #identity:
  #  image: identity
  #  container_name: identity
  #  depends_on:
  #      - identity_db
  #  build:
  #      context: .
  #      dockerfile: Dockerfile.IdentityApi
  #  ports:
  #      - '3030:80'
  identity_db:
    image: postgres:latest
    container_name: identity_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - identity_db_data:/var/lib/postgresql/data/
  #science:
  #  image: science
  #  container_name: science
  #  depends_on:
  #      - science_db
  #  build:
  #      context: .
  #      dockerfile: Dockerfile.ScienceApi
  #  ports:
  #      - '3031:80'
  science_db:
    image: postgres:latest
    container_name: science_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - science_db_data:/var/lib/postgresql/data/
  #student:
  #  image: student
  #  container_name: student
  #  depends_on:
  #      - student_db
  #  build:
  #      context: .
  #      dockerfile: Dockerfile.StudentApi
  #  ports:
  #      - '3032:80'
  student_db:
    image: postgres:latest
    container_name: student_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - student_db_data:/var/lib/postgresql/data/

  #chat:
  #  image: chat
  #  container_name: chat
  #  depends_on:
  #      - chat_db
  #      - rabbitmq
  #  build:
  #      context: .
  #      dockerfile: Dockerfile.ChatApi
  #  ports:
  #      - '3033:80'
  #  networks:
  #    - internal

  chat_db:
    image: postgres:latest
    container_name: chat_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - chat_db_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal

volumes:
  identity_db_data:
  science_db_data:
  student_db_data:
  chat_db_data: